server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9000

spring:
  datasource:
    url: jdbc:oracle:thin:@211.38.173.250:1521:xe
    username: TT
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
#  type-aliases-package: com.example.board.model
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml